# dsn: "postgres://127.0.0.1/go_restful?sslmode=disable&user=postgres&password=postgres"
dsn: "host=0.0.0.0 port=5432 user=postgres dbname=notes password=postgres sslmode=disable"
jwt_signing_key: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
