# values.yaml

zookeeper:
  image: confluentinc/cp-zookeeper:7.3.2
  ports:
    - targetPort: 31000
      publishedPort: 31000
  env:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000
    KAFKA_JMX_HOSTNAME: "localhost"
    KAFKA_JMX_PORT: 31000

kafka:
  image: confluentinc/cp-kafka:7.3.2
  ports:
    - targetPort: 9092
      publishedPort: 9092
    - targetPort: 31001
      publishedPort: 31001
  dependsOn:
    - zookeeper
  env:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
    KAFKA_JMX_HOSTNAME: "localhost"
    KAFKA_JMX_PORT: 31001
