{{ if .Values.service.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress-service
    app.kubernetes.io/version: "{{ .Values.service.image.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.service.ingress.path }}
            pathType: {{ .Values.service.ingress.pathType }}
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
